### ISSUE TITLE
Make a Javascript version

### ISSUE THREAD

**Issue by Actarus-0** [SafiMed/resize_s3_images#1]
Good job :p 

Why not have a javascript version of this script? 
Would make it easy to deploy on Netlify Functions instead of Amazon Lambda directly.

**Comment by SafiMed** [comment]
Good idea, Netlify Functions are too effective, but this source code was only related to this blog: https://www.obytes.com/blog/2019/image-resizing-on-the-fly-with-aws-lambda,-api-gateway,-and-s3-storage/
Here I am using AWS Lambda with AWS API Gateway & S3 storage, It is good to go with Lambdas since you have triggers and to stay on AWS.
